# .streamlit/secrets.toml

[snowflake]
user = "BSHARMA1503"
password = "Bsharma1503"
account = "ljqrasm-wr73660"
warehouse = "COMPUTE_WH"
database = "COMPARE_DATABASE"
schema = "APP"
role = "Comp_Table"


